apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    App: jenkins
  finalizers:
    - kubernetes.io/pvc-protection
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  volumeMode: Filesystem
