apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: json-filter
  name: json-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: json-filter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: json-filter
    spec:
      containers:
        - env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "5000"
            - name: QUEUE_RESTAPI
              value: restapi
            - name: QUEUE_SLACK
              value: slack
            - name: RMQ_HOST
              value: rabbitmq
            - name: RMQ_LOGIN
              value: devops
            - name: RMQ_PASS
              value: softserve
            - name: RMQ_PORT
              value: "5672"
          image: json-filter
          name: json_filter
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
