apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-to-db
  name: rabbit-to-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit-to-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit-to-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: issuedb
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PW
              value: Init1234
            - name: POSTGRES_USER
              value: issueuser
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_PW
              value: softserve
            - name: RABBIT_QUEUE
              value: restapi
            - name: RABBIT_USER
              value: devops
          image: rabbit-to-db
          name: rabbit_to_db
          resources: {}
      restartPolicy: Always
status: {}
