apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: slack
  name: slack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slack
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: slack
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_PW
              value: softserve
            - name: RABBIT_QUEUE
              value: slack
            - name: RABBIT_USER
              value: devops
            - name: SLACK_BUG
              value: '#'
            - name: SLACK_TC
              value: '#'
            - name: SLACK_URL
            - name: SLACK_US
              value: '#'
          image: slack
          name: slack
          resources: {}
      restartPolicy: Always
status: {}
