apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    App: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      App: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        App: frontend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: issuedb
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PW
              value: Init1234
            - name: POSTGRES_USER
              value: issueuser
            - name: RESTAPI_HOST
              value: restapi
            - name: RESTAPI_PORT
              value: "5000"
          image: frontend
          name: frontend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
