# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone 
  - https://github.com/DevOps-Kv-116/frontend.git
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag
  - gcr.io/${PROJECT_ID}/frontend:frontend
  - --tag
  - gcr.io/${PROJECT_ID}/frontend:latest
  - .
  dir: frontend
images:
  - 'gcr.io/${PROJECT_ID}/frontend:frontend'
  - 'gcr.io/${PROJECT_ID}/frontend:latest'

tags: ['cloud-builders']
